### ISSUE TITLE
"set" procedure not accepting input of parameter_list type 

### ISSUE THREAD

**Issue by trmwzm** [nncarlson/petaca#13]
... as a way of appending an existing list to another one, as a sublist. ... thank you for the library!

**Comment by trmwzm** [comment]
Hello Neal.  If I have 2 parameter_list(s), let's say read from JSONs,  I am looking to add a type bound procedure to be able to do:
``
type(parameter_list) :: p, p1, p2

call parameter_list_from_json_stream(json_1_unit, p1)
call parameter_list_from_json_stream(json_2_unit, p2)

call p%set ('json 1', p1)
call p%set ('json 2', p2)
``
 Should be relatively easy using recursion and the iterators already in library (?)  I will try to give it a go.

**Comment by nncarlson** [comment]
I think you should be able to do something like that already:
```fortran
type(parameter_list) :: p
type(parameter_list), pointer :: p1, p2

p1 => p%sublist('json 1')
p2 => p%sublist('json 2')

call parameters_from_json_stream(json1_unit, p1)
call parameters_from_json_stream(json2_unit, p2)
```
Note the use of `parameters_from_json_stream` instead of `parameter_list_from_json_stream`. The latter takes a pointer as an argument which it allocates and fills internally. The former takes a preexisting parameter list and adds to it.

That said, if one had an *existing* parameter list pointer p1, it would be very useful to be able to make it a *new* sublist of a parameter list p. So something like this:
```fortran
call parameter_list_from_json_stream(json1_unit, p1)
...
call p%set_sublist('json 1', p1)
```
I've wanted this myself on several occasions. It's not always convenient or possible to create the empty sublist first and then fill it. Is this what you are looking for?  This would be very easy to add.

**Comment by trmwzm** [comment]
Yes, creating a sublist and subsequently filling it would be a workaround. The use case I was thinking of is a hierarchy of list which mirrors that of class composition.  A class would have a constructor using a plist as a unique argument, and a "to_plist()" serialization.  I can easily modify "to_plist" to take a pre-allocated plist as additional argument. Thank you very much!

**Comment by nncarlson** [comment]
I'm intrigued by your serialization use case. If you can, and when you feel ready, I'd like to hear more about it.
