### ISSUE TITLE
Test failures on Mac w/NAG

### ISSUE THREAD

**Issue by pbrady** [nncarlson/petaca#21]
```
90% tests passed, 2 tests failed out of 20

Total Test time (real) =   3.87 sec

The following tests FAILED:
	  1 - fortran_dynamic_loader (Failed)
	  9 - secure_hash (Failed)
Errors while running CTest
```

**Comment by nncarlson** [comment]
The failure of 1 doesn't surprise me.  The test (or even the implementation of that module) may be very Linux specific.  If you could figure out what macOS needs that would be great.

The failure of 9 may be due to the test needing to run `md5sum` and `sha1sum` system commands. Again perhaps too linux-centric.  Any additional failure info (`ctest -V`)?
